App_Cloud/urls.py
from django.urls import path
from . import views

app_name = 'App_Cloud'

urlpatterns = [
    path("",views.index,name="home"),
    path("register",views.register,name="register"),
    path("login",views.login_user,name="loginUser"),
    path("logout",views.logout_user,name="logoutuser"),
    path("signup",views.signup,name="signup"),
    path('viewprofile',views.viewprofile,name="viewprofile"),
    path("help",views.help,name="help"),
    path("search",views.search,name="search"),
    path("catsearch",views.catsearch,name="catsearch"),
    path("searchfood",views.searchfood,name="searchfood"),
    path("tables/<int:id>/",views.tables,name="tables"),
    path("booknow/<int:res>/<int:tb>/",views.booknow,name="booknow"),
    path("orderfood/<int:id>/",views.orderfood,name="orderfood"),
    path("restaurants/<int:id>/",views.visitresturants,name="visitresturants"),
]

CORE/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("App_Cloud.urls"))
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

App_Cloud/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# USER
class MyUser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)  
    address = models.CharField(max_length=1000,default="None")
    photo = models.ImageField(null=False,blank=False,upload_to="user")
    phone = models.CharField(max_length=1000,default="None")
    trusted = models.BooleanField(default=False)

# Category
class RestaurantCategories(models.Model):
    category = models.CharField(max_length=400,default="Nothing")
    def __str__(self) -> str:
        return self.category
    
# Restaurant    
class Restaurant(models.Model):
    name = models.CharField(max_length=1000,default="None")
    location = models.CharField(max_length=100,default="None")
    category = models.ForeignKey(RestaurantCategories, on_delete=models.CASCADE,default=1)
    min_price = models.IntegerField(default=0)
    max_price = models.IntegerField(default=0)
    seats = models.IntegerField(default=0)
    tables = models.IntegerField(default=0)
    photo = models.ImageField(null=False,blank=False,upload_to="restaurant")
    def __str__(self) -> str:
        return self.name

class FoodItem(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE,default=1)
    title = models.CharField(max_length=1000,default="None")
    price = models.IntegerField(default=0)
    photo = models.ImageField(null=False,blank=False,upload_to="food")
    def __str__(self) -> str:
        return self.title

class Table(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE,default=1)
    seats = models.IntegerField(default=0)
    booking_status = models.BooleanField(default=False)
    

class BookingRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE,default=1)
    table = models.ForeignKey(Table, on_delete=models.CASCADE,default=1)
    timestamp = models.DateTimeField(auto_now_add=True)

class FoodOrder(models.Model):
    item = models.ForeignKey(FoodItem, on_delete=models.CASCADE,default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    bill = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    order_status = models.BooleanField(default=False)

App_Cloud/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Restaurant, FoodItem, MyUser, Table, BookingRecord, FoodOrder,RestaurantCategories
from django.db.models import Q

# Create your views here.

def index(request):
    rests = Restaurant.objects.all()
    cats = RestaurantCategories.objects.all()
    context = {
        "rests" : rests,
        "cats" : cats
    }
    return render(request,"App_Cloud/index.html",context)


def help(request):
    return redirect(f"https://wa.me/+8801521430255?text=Need Some Help?")

def register(request):
    # form = NewUserForm()
    return render(request,"register.html")

def login_user(request):
    if request.method == "POST":
        user = request.POST.get("user")
        password = request.POST.get("password")
        userr = authenticate(request,username=user,password=password)
        if userr is not None:
            login(request,userr)
            return redirect("App_Cloud:viewprofile")
        else:
            messages.success(request, 'Your username or password is wrong!')
            return redirect("App_Cloud:register")       
    # return render(request,"user/index.html")

def logout_user(request):
    logout(request)
    return redirect("App_Cloud:register")

def signup(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        phone = request.POST["phone"]
        address = request.POST["address"]
        photo = request.FILES.get("photo")
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]
        if password1 == password2:
            usr = User.objects.create_user(username=username, password=password1,email=email)
            usr.save()
            obj = MyUser.objects.create(user=usr,address=address,photo=photo,phone=phone)
            obj.save()
            user = authenticate(request,username=username,password=password1)    
            login(request,user)
        else:
            messages.success(request, 'Password not similar')
            return redirect("App_Cloud:register")     
        return redirect("/register")
    
@login_required(login_url='/register')   
def viewprofile(request):
    usr = User.objects.get(id=request.user.id)
    objects = BookingRecord.objects.filter(user=usr)
    orders = FoodOrder.objects.filter(user=usr)
    context = {
        "objects" : objects,
        "orders" : orders
    }
    
    return render(request,"viewprofiel.html",context)
def search(request):
    query = request.GET.get("search")
    if query != "":
        rests = Restaurant.objects.filter(
        Q(name__icontains=query) | Q(location__icontains=query) 
    )
                        
    else:
        rests = Restaurant.objects.all()
    
    context ={
        "rests" : rests
    }
    return render(request,"result.html",context)
def catsearch(request):
    query = request.GET.get("search")
    cat = RestaurantCategories.objects.get(id=query)
    rests = Restaurant.objects.filter(category=cat)
    
    context ={
        "rests" : rests
    }
    return render(request,"result.html",context)
def searchfood(request):
    query = request.GET.get("search")
    if query != "":
        items = FoodItem.objects.filter(
        Q(title__icontains=query) | Q(price__icontains=query) 
    )
                        
    else:
        items = FoodItem.objects.all()
    
    context ={
        "items" : items
    }
    return render(request,"App_Cloud/foodresult.html",context)

def visitresturants(request,id):
    rest = Restaurant.objects.get(id=id)
    tables = Table.objects.filter(restaurant=rest)
    total_tables = tables.count()
    seats = 0
    for t in tables:
        seats = seats + t.seats
    items = FoodItem.objects.filter(restaurant=rest)
    context = {
        "items" : items,
        "rest" : rest,
        "total_tables" : total_tables,
        "seats" : seats
    }
    return render(request,"App_Cloud/visitresturants.html",context)

def tables(request,id):
    rest = Restaurant.objects.get(id=id)
    tables = Table.objects.filter(restaurant=rest)
    context = {
        "rest" : rest,
        "tables" : tables
    }
    return render(request,"App_Cloud/tables.html",context)


def booknow(request,res,tb):
    tab = Table.objects.get(restaurant=res,id=tb)
    tab.booking_status = True
    tab.save()
    rest = Restaurant.objects.get(id=res)
    tabl = Table.objects.get(id=tb)
    us = User.objects.get(id=request.user.id)
    obj = BookingRecord.objects.create(user=us,restaurant=rest,table=tabl)
    obj.save()
    return redirect("App_Cloud:viewprofile")

def orderfood(request,id):
    item = FoodItem.objects.get(id=id)
    us = User.objects.get(id=request.user.id)
    obj = FoodOrder.objects.create(item=item,user=us,bill=item.price)
    obj.save()
    return redirect("App_Cloud:viewprofile")

templates/App_Cloud/foodresult.html
{% if items %}

<div class="row mt-4">
    {% for item in items %}
    
    <div class="col-md-3 mt-2">
        {% comment %} <a href="/{{item.tname}}"> {% endcomment %}
            <div class="card shadow-0 border mt-2">
            {% comment %} {{item.photo}} {% endcomment %}
                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                  <img src="/media/{{item.photo}}" class="img-fluid"/>
                  <a href="#!">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                  </a>
                </div>
                <div class="card-body">
                  <h4 class="card-title">{{item.title}}</h4>
                  <p class="card-text" style="font-size:13px;"><i class="fas fa-money-bill"></i> price: {{item.price}}<p>
                  <a href="/orderfood/{{item.id}}/" class="btn btn-secondary">Order Now</a>
                </div>
              </div>
    {% comment %} </a> {% endcomment %}
    </div>

    {% endfor %}
    
</div>

{% else %}
<div class="text-center mt-3">
    Nothing To Show!
</div>
{% endif %}

templates/App_Cloud/index.html
{% extends "basic.html" %}
{% block title %}Restaurants{% endblock title %}

{% block css %}
.main-section{
    height:60vh;
    <!-- background: rgb(114,2,199); -->
    background: #123953;
    background: linear-gradient(180deg, rgba(18, 58, 84,1) 23%, rgba(11, 112, 180, 2) 70%);
    {% comment %} border: 2px solid red; {% endcomment %}
}
.search{
    width:70%;
    background-color : white;
    
    {% comment %} border:2px solid green; {% endcomment %}
    margin:auto;
    margin-top:40px;
    height:50px;
    padding:10px;
    {% comment %} border-bottom:2px solid #7202c7; {% endcomment %}
}
.search:hover{
    border:1px solid #7202c7; 
}
.srch{
    width:100%;
    border:none;
    outline:none;
    font-size:15px;
    margin-top:3px;
}
.bd{
    border-bottom:3px solid #7202c7;
}
.toolmenu{
    background-color:transparent;
    padding: 7px;
    margin-top:30px;
    width:17vw;
    border-radius:19px;
}
.toolmenu ul{
    list-decoration:none;
}
.toolmenu a{
    padding:4px;
    
}
.toolmenu a:hover{
    color:#7202c7;
    border-bottom:2px solid #7202c7;
}
.s-icon{
    margin-top:7px;
}
.toptext{
    margin-top:35px;
    font-size:50px;

}
@media screen and (max-width: 780px) {
    .search{
        width:100%;
        margin-top:25px;
        padding:7px;
    }
    .toolmenu{
        width:60vw;
    }
    .toptext{
        font-size:40px;
        margin-top:10px;
    }
}
{% endblock css %}
{% block content %}

    <div class="main-section text-center p-4 ">
        <h1 class="text-white toptext">Available <span> </span> Restaurants</h1>
        <!-- <p class="text-white">Good Food Is Foundation Of Genius Souls!</p> -->
        <div class="search shadow-3  card">
            <div class="row">
                <div class="col-3 mt-1">
                    <i class="fas fa-location-crosshairs d-md-inline-block d-none"></i>
                    <select class="" aria-label="Default select example" style="border:none;outline:none;" name="search" hx-get="/search" hx-trigger="click" hx-target="#result">
                        <option selected value="">Location</option>
                        {% for re in rests %}
                        <option value="{{re.location}}">{{re.location}}</option>
                        {% endfor %}
                        
                      </select>
                </div>
                <div class="col-4 mt-1">
                    <i class="fas fa-bars-staggered d-md-inline-block d-none"></i>
                    <select class="" aria-label="Default select example" style="border:none;outline:none;" name="search" hx-get="/catsearch" hx-trigger="click" hx-target="#result">
                        <option selected>Category</option>
                        {% for cat in cats %}
                        <option value="{{cat.id}}">{{cat}}</option>
                        {% endfor %}
                        
                      </select>
                </div>
                
                
                <div class="col-md-4 col-5">
                    <input type="text" class="d-inline-block srch" placeholder="Search for Restaurants Name Here" hx-get="/search" hx-trigger="keyup" hx-target="#result" name="search" id="inputBox">
                    
                </div>
                <div class="col-1 d-md-inline-block d-none">
                    <i class="fas fa-magnifying-glass s-icon p-color"></i>
                </div>
            </div>
            
            
            
        </div>
        <div>
            <div class="row">
                <div class="col-md-4">
                    
                </div>
            </div>
            

        </div>

        <div class="text-center mt-2">
            <div id="output" class="text-white"></div>
        </div>
        
        {% comment %} <div class="toolmenu mx-auto">
            <a href="#" class="text-dark" >All Tools</a>
            <a href="#" class="text-dark">Text</a>
            <a href="#" class="text-dark">Number</a> 
            
                
        </div> {% endcomment %}
    </div>
    {% comment %} <hr> {% endcomment %}
    <div class="container">
        <div id="result">
            {% include "result.html" %}
        </div>
   
</div>
<script>
    const inputBox = document.getElementById("inputBox");
const output = document.getElementById("output");
let timer;

inputBox.addEventListener("input", function() {
  clearTimeout(timer);
  output.innerText = `You are Searching: ${inputBox.value}`;
  timer = setTimeout(function() {
    output.innerText = "";
  }, 2000);
});

</script>

{% endblock content %}

templates/App_Cloud/tables.html
{% extends "basic.html" %}
{% block content %}
<div class="container">
    <div class="card shadow-0 border p-md-4 p-2 mt-2">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Table ID</th>
                <th scope="col">Number of Seats</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% if tables %}
                {% for t in tables %}
                <tr>
                    <th scope="row">{{t.id}}</th>
                    <td>{{t.seats}}</td>
                    {% if t.booking_status == False %}
                    <td>Avaible <i class="fas fa-check text-success"></i></td>
                    <td><a href="/booknow/{{rest.id}}/{{t.id}}/" class="btn btn-sm btn-success">Book Now</a></td>
                    {% else %}
                    <td>Booked <i class="fas fa-circle-xmark text-danger"></i></td>
                    <td>wait for it</td>
                    {% endif %}
                    
                    
                  </tr>
                  {% endfor %}
                {% else %}
                No data found!
                {% endif %}
              
              
            </tbody>
          </table>
    </div>
</div>
{% endblock content %}

templates/register.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}
<div class="container mb-4 mb-md-0">
<div class="mt-3">
<div class="row">
  <div class="col-md-6 d-md-block d-none mt-2">
    <img src="/media/Auth.jpg"
      class="img-fluid" alt="Phone image">
  </div>
  <div class="col-md-6">
    <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
      <li class="nav-item" role="presentation">
        <a
          class="nav-link active"
          id="tab-login"
          data-mdb-toggle="pill"
          href="#pills-login"
          role="tab"
          aria-controls="pills-login"
          aria-selected="true"
          >Login</a
        >
      </li>
      <li class="nav-item" role="presentation">
        <a
          class="nav-link"
          id="tab-register"
          data-mdb-toggle="pill"
          href="#pills-register"
          role="tab"
          aria-controls="pills-register"
          aria-selected="false"
          >Register</a
        >
      </li>
    </ul>
    <!-- Pills navs -->
    
    <!-- Pills content -->
    <div class="tab-content">
      <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
        <form action="{% url 'App_Cloud:loginUser' %}" method="post">{% csrf_token %}
          {% comment %} <div class="text-center mb-3">
            <p>Sign in with:</p>
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-facebook-f"></i>
            </button>
    
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-google"></i>
            </button>
    
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-twitter"></i>
            </button>
    
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-github"></i>
            </button>
          </div>
    
          <p class="text-center">or:</p> {% endcomment %}
    
          <!-- Email input -->
          <div class="form-outline mb-4">
            <input type="text" id="loginName" class="form-control text-primary" name="user"/>
            <label class="form-label text-primary" for="loginName">Username</label>
          </div>
    
          <!-- Password input -->
          <div class="form-outline mb-4">
            <input type="password" id="loginPassword" class="form-control text-primary" name="password"/>
            <label class="form-label text-primary " for="loginPassword">Password</label>
          </div>
    
          <!-- 2 column grid layout -->
          <div class="row mb-4">
            <div class="col-md-6 d-flex justify-content-center">
              <!-- Checkbox -->
              <div class="form-check mb-3 mb-md-0">
                <input class="form-check-input" type="checkbox" value="" id="loginCheck" checked />
                <label class="form-check-label" for="loginCheck"> Remember me </label>
              </div>
            </div>
            
           
            <div class="col-md-6 d-flex justify-content-center">
              <!-- Simple link -->
              <a href="#!" data-mdb-ripple-color="dark" data-mdb-toggle="modal" data-mdb-target="#exampl">Forgot password?</a>
            </div>
          </div>
          {% if messages %}
          {% for message in messages %}
  
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            {% comment %} <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> {% endcomment %}
          </div>
          {% endfor %}
          {% endif %}
          <!-- Submit button -->
          <button type="submit" class="btn btn-primary btn-block mb-4">Log in</button>
    
          <!-- Register buttons -->
          <div class="text-center">
            <p>Ask for <a href="{% url 'App_Cloud:help' %}">Help</a>?</p>
          </div>
        </form>
      </div>

      <!--================== REGISTER ================== -->
      <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="tab-register">
        <form action="{% url 'App_Cloud:signup' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
          {% comment %}
           <div class="text-center mb-3">
            <p>Sign up with:</p>
            <button type="button" class="btn btn-primary btn-floating mx-1 disabled" disabled>
              <i class="fab fa-facebook-f"></i>
            </button>
    
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-google"></i>
            </button>
    
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-twitter"></i>
            </button>
    
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-github"></i>
            </button>
          </div>
    
          <p class="text-center">or:</p> 
          {% endcomment %}
    
           <!-- Name input -->
          {% comment %} <div class="form-outline mb-4">
            {{ form.username }}
            {% comment %} <input type="text" id="firstName" class="form-control" /> 
            <label class="form-label" for="firstName">First Name</label>
          </div> 
          <div class="form-outline mb-4">
            {{ form.username }}
            {% comment %} <input type="text" id="lastName" class="form-control" />
            <label class="form-label" for="lastName">Last Name</label>
          </div>  {% endcomment %}
    
          <!-- Username input -->
          <div id="res">
            {% include "wcpartial.html" %}  
          </div>
          <div id="resp">
            {% include "wcpartial.html" %}  
          </div>
          <div class="form-outline mb-4">           
              <input type="text" id="registerUsername" class="form-control text-primary" name="username"/>
              <label class="form-label text-primary" for="registerUsername">Username</label>           
          </div>
          <!-- Email input -->
          <div class="form-outline mb-4">
            
            <input type="email" id="registerEmail" class="form-control text-primary" name="email" />
            <label class="form-label text-primary" for="registerEmail">Email</label>
          </div>
          <div class="form-outline mb-4">
            
            <input type="text" id="registerphone" class="form-control text-primary" name="phone" />
            <label class="form-label text-primary" for="registerphone">Phone</label>
          </div>
          <div class="form-outline mb-4">
            
            <input type="text" id="registeraddress" class="form-control text-primary" name="address" />
            <label class="form-label text-primary" for="registeraddress">Address</label>
          </div>

          <div class="form-outline mb-4">
            
            <input type="file" id="registerphoto" class="form-control text-primary" name="photo" />
            <label class="form-label text-primary" for="registerphoto"></label>
          </div>
          <!-- Password input -->
          <div class="form-outline mb-4">
            
            <input type="password" id="registerPassword" class="form-control text-primary" name="password1"/>
            <label class="form-label text-primary" for="registerPassword">Password</label>
          </div>
    
          <!-- Repeat Password input -->
          <div class="form-outline mb-4">
            {% comment %} {{ form.password2 }} {% endcomment %}
            <input type="password" id="registerRepeatPassword" class="form-control text-primary" name="password2"/>
            <label class="form-label text-primary" for="registerRepeatPassword">Repeat password</label>
          </div>      
          <!-- Submit button -->      
            <button type="submit" class="btn btn-primary btn-block mb-3">Register</button>     
        </form>
      </div>
    </div>
    <!-- Pills content -->
  </div>
</div>

</div>
<div class="modal top fade" id="exampl" tabindex="-1" aria-labelledby="exampl"
     aria-hidden="true" data-mdb-backdrop="true" data-mdb-keyboard="true">
    <div class="modal-dialog" style="width: 300px;">
        <div class="modal-content text-center">
            <div class="modal-header h5 text-white bg-success justify-content-center">
                Password Reset
            </div>
            <div class="modal-body px-5">
                <p class="py-2">
                    Use Your Account Email.
                </p>
              <form action="/resetpassword" method="Post">{% csrf_token %}
                  <input type="text" id="type" class="form-control my-3" name="username" placeholder="Enter Username"/>
                  <input type="text" name="newpwd" id="newpwd" placeholder="New Password" class="form-control mb-2">               
                  <button type="submit" class="btn btnexp w-100">Reset password</button>
              </form>
                
            </div>
            </div>
        </div>
    </div>
</div>  
</div>
  {% endblock content %}

templates/result.html
{% if rests %}

<div class="row mt-4">
  {% for re in rests %}

  <div class="col-md-3 mt-2">
    <a href="/{{tool.tname}}">
      <div class="card">
        <div
          class="bg-image hover-overlay ripple"
          data-mdb-ripple-color="light"
        >
          <img src="/media/{{re.photo}}" class="img-fluid" />
          <a href="#!">
            <div
              class="mask"
              style="background-color: rgba(251, 251, 251, 0.15)"
            ></div>
          </a>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{re.name}}</h5>
          <p class="card-text" style="font-size: 11px">
            <i class="fas fa-location-dot"></i> Location: {{re.location}}
          </p>
          <p>
            <a href="/restaurants/{{re.id}}/"
              >Visit Now <i class="fas fa-arrow-right-long text-muted"></i
            ></a>
          </p>
        </div>
      </div>
    </a>
  </div>

  {% endfor %}
</div>

{% else %}
<div class="text-center mt-3">Nothing To Show!</div>
{% endif %}

templates/viewprofiel.html
{% extends 'basic.html' %}
{% block content %}

<div class="container mt-4 mb-md-0 mb-5">
  <div class="row">
    <div class="col-md-4">
      <div class="card" style="border-radius: 25px; background-color: #061a20;">
        <div class="card-body p-4 text-white">
          <div>
            <h6 class="mb-4">Your Profile</h6>
            <div class="d-flex align-items-center justify-content-between mb-3">
              <p class="small mb-0">Bookings</p>
              
              <p class="fw-bold mb-0"><i class="fas fa-hand-holding-usd me-2"></i>{{credit}}</p>
            </div>
          </div>
          <div class="d-flex align-items-center mb-4">
            <div class="flex-shrink-0">
              <img src="/media/{{request.user.myuser.photo}}"
                alt="Generic placeholder image" class="img-fluid rounded-circle border border-dark border-2"
                style="width: 70px; height: 70px;">
            </div>
            <div class="flex-grow-1 ms-3">
              <div class="d-flex flex-row align-items-center mb-2">
                <p class="mb-0 me-2">{{request.user.username|capfirst}}</p>
                <ul class="mb-0 list-unstyled d-flex flex-row" style="color: #d6ebda;">
                  <li>
                    <i class="fas fa-star fa-xs"></i>
                  </li>
                  <li>
                    <i class="fas fa-star fa-xs"></i>
                  </li>
                  <li>
                    <i class="fas fa-star fa-xs"></i>
                  </li>
                  <li>
                    <i class="fas fa-star fa-xs"></i>
                  </li>
                  <li>
                    <i class="fas fa-star fa-xs"></i>
                  </li>
                </ul>
              </div>
              <div>       
                <a href="{% url 'App_Cloud:logoutuser' %}" type="button" class="btn btn-outline-white btn-rounded btn-sm"
                  data-mdb-ripple-color="white">Logout</a>
                  <button  type="button" class="btn btn-outline-white btn-rounded btn-sm"
                  data-mdb-ripple-color="white" data-mdb-toggle="modal" data-mdb-target="#exampl">reset Password</button>    
              </div>
            </div>
          </div>
          <hr>
          <a href="/" type="button" class="btn btn-success btn-rounded btn-block btn-lg"><i
              class="far fa-clock me-2"></i>Book Now</a>
        </div>
      </div>
    </div>
    <div class="col-md-8 mt-md-0 mt-3">
        <div class="card shadow-0 border p-2">

       
{% if objects %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">Table ID</th>
        <th scope="col">Restaurant</th>
        <th scope="col">Date Time</th>
        
      </tr>
    </thead>
    <tbody>
        
        {% for obj in objects %}
        <tr>
            <th scope="row">{{obj.table.id}}</th>
            <td>{{obj.restaurant}}</td>
            <td>{{obj.timestamp}}</td>         
          </tr>
          {% endfor %}
    </tbody>
  </table>
{% else %}
<div class="text-center py-5">
  <h1>No Bookings Yet!.</h1>
  <a href="/" class="btn btn-primary btn-sm mt-2">Book Now</a>
</div> 
  {% endif %}
</div>   
    </div>
  </div>



<div class="modal top fade" id="exampl" tabindex="-1" aria-labelledby="exampl"
     aria-hidden="true" data-mdb-backdrop="true" data-mdb-keyboard="true">
    <div class="modal-dialog" style="width: 300px;">
        <div class="modal-content text-center">
            <div class="modal-header h5 text-white bg-success justify-content-center">
                Password Reset
            </div>
            <div class="modal-body px-5">
                <p class="py-2">
                    Enter 8 Digit strong password.Must include Numbers letters and punctuations.
                </p>
                <form action="/resetpassword">
                    <input type="text" id="type" class="form-control my-3" name="password" placeholder="Enter New Password"/>
                    
                
                <button type="submit" class="btn btnexp w-100">Reset password</button>
              </form>
                
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="card shadow-0 border p-md-4 p-2 mt-2">
        <h4>
            Orders History
        </h4>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Food Item</th>
                <th scope="col">Bill</th>
                <th scope="col">Date Time</th>
                <th scope="col">Status</th>
                
              </tr>
            </thead>
            <tbody>
                
                {% for ord in orders %}
                <tr>
                    <th scope="row">{{ord.item}}</th>
                    <td>{{ord.bill}}</td>
                    <td>{{ord.timestamp}}</td>
                    {% if ord.order_status == True %}
                    
                    <td><i class="fas fa-check text-success"></i></td>
                    {% else %}
                    <td><i class="fas fa-circle-xmark text-danger"></i></td>
                    
                    {% endif %}
                    
                  </tr>
                  {% endfor %}
              
              
              
            </tbody>
          </table>

    </div>
</div>



</div>
{% endblock content %}